import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="flex flex-column min-h-screen">
      <header className="bg-white shadow-md p-4 mb-8"> /* Added bottom margin to header */
        <nav className="container mx-auto flex justify-between">
          <div>
            <Link href="/">
              <a className="text-xl font-bold">Auduate</a>
            </Link>
          </div>
          <div>
            <Link href="/login">
              <a className="p-2">Login</a>
            </Link>
            <Link href="/signup">
              <a className="p-2">Sign Up</a>
            </Link>
          </div>
        </nav>
      </header>
      <main className="container mx-auto p-4 flex-grow"> /* Ensured consistent padding */
        {children}
      </main>
      <footer className="bg-white shadow-md p-4 text-center">
        <p>&copy; {new Date().getFullYear()} Auduate. All rights reserved.</p>
      </footer>
    </div>
  );
}
